### ISSUE TITLE
Fetching conversation history 

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#117] opened 2017-10-31 03:04 UTC
*Description*
`GET` method at `/conversation/:id` is randomly lagged with the following log
```
backend_service_1  | [2017-10-31 03:00:27 +0000] [34] [DEBUG] GET /conversation/20
backend_service_1  | [2017-10-31 03:01:01 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:25)
backend_service_1  | [2017-10-31 03:01:01 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:34)
backend_service_1  | [2017-10-31 03:01:01 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:36)
backend_service_1  | [2017-10-31 03:01:01 +0000] [25] [INFO] Worker exiting (pid: 25)
backend_service_1  | [2017-10-31 03:01:01 +0000] [36] [INFO] Worker exiting (pid: 36)
backend_service_1  | [2017-10-31 03:01:01 +0000] [34] [INFO] Worker exiting (pid: 34)
backend_service_1  | Creating database tables from models.py
backend_service_1  | Creating database tables from models.py
backend_service_1  | Creating database tables from models.py
backend_service_1  | [2017-10-31 03:01:01 +0000] [40] [INFO] Booting worker with pid: 40
backend_service_1  | [2017-10-31 03:01:01 +0000] [1] [DEBUG] 1 workers
backend_service_1  | [2017-10-31 03:01:01 +0000] [42] [INFO] Booting worker with pid: 42
backend_service_1  | [2017-10-31 03:01:01 +0000] [44] [INFO] Booting worker with pid: 44
backend_service_1  | [2017-10-31 03:01:01 +0000] [1] [DEBUG] 3 workers
backend_service_1  | [2017-10-31 03:01:32 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:40)
backend_service_1  | [2017-10-31 03:01:32 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:42)
backend_service_1  | [2017-10-31 03:01:32 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:44)
backend_service_1  | /usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
backend_service_1  |   'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
backend_service_1  | [2017-10-31 03:01:32 +0000] [40] [INFO] Worker exiting (pid: 40)
backend_service_1  | /usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
backend_service_1  |   'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
backend_service_1  | [2017-10-31 03:01:32 +0000] [42] [INFO] Worker exiting (pid: 42)
backend_service_1  | Creating database tables from models.py
backend_service_1  | Creating database tables from models.py
backend_service_1  | Creating database tables from models.py
backend_service_1  | /usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
backend_service_1  |   'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
backend_service_1  | [2017-10-31 03:01:32 +0000] [44] [INFO] Worker exiting (pid: 44)
backend_service_1  | [2017-10-31 03:01:32 +0000] [49] [INFO] Booting worker with pid: 49
backend_service_1  | [2017-10-31 03:01:32 +0000] [1] [DEBUG] 1 workers
backend_service_1  | [2017-10-31 03:01:32 +0000] [51] [INFO] Booting worker with pid: 51
backend_service_1  | [2017-10-31 03:01:32 +0000] [53] [INFO] Booting worker with pid: 53
backend_service_1  | [2017-10-31 03:01:32 +0000] [1] [DEBUG] 3 workers
backend_service_1  | /usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
backend_service_1  |   'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
backend_service_1  | [2017-10-31 03:01:33 +0000] [51] [DEBUG] GET /conversation/20
```

*Scope of Work*
- [ ] debug and fix the performance issue

*Acceptance Criteria*
- the rest call doesn't hang

*Related Issues*
- #66

**Comment by Vynny** [comment] 2017-11-01 16:04
Can't reproduce locally, and lance tells me it magically fixed itself in prod.

I did some research and found that the psycopg2 driver we're using for postgres doesn't like 'green' threads.
A potential solution if this becomes a problem in the future is to use https://bitbucket.org/dvarrazzo/psycogreen/. It provides the psycogreen.gevent module which patches the psycopg driver to be greenlet friendly. In addition, we'd have to change our gunicorn worker type to gevent.

**Comment by Vynny** [comment] 2017-11-01 16:05
Closing this issue, will reopen if it persists.

**Closed as completed by Vynny** 2017-11-01 16:05 UTC
Labels: Bug
