### ISSUE TITLE
Determine claim validity

### ISSUE THREAD

**Issue by dodoels** [Cyberjusticelab/JusticeAI#16] opened 2017-09-28 00:41 UTC
*Description*
- As a user, I want the system to tell me if my claim is valid

*Scope of Work*

*Acceptance Criteria*

*Story Points*
- 100

*Priority*
- High

*Risk*
- High

**Comment by arekmano** [comment] 2017-10-13 03:15
Original Comment: "Define receivability criterias. Easier to be certain if invalid than valid."

**Comment by arekmano** [comment] 2017-10-13 03:19
How do we proceed with this user story. Is validity to be determined based on facts obtained about the case, which is then compared with given laws? This approach would allow us to determine with a higher probability that a claim is valid, but requires a lot of law domain knowledge.

Another approach would be to extract facts from the user and compare these with precedents' facts, using machine learning techniques. This approach requires less domain knowledge, but will have higher false positives and false negatives.

**Comment by naregeff** [comment] 2017-10-13 18:08
Could it be a combination of both methods? Try to be as exhaustive as possible when defining general receivability criteria (ex. statute of limitations, interest, written notice, demand letter, verbal notice, existence of a lease agreement, etc.) and we can then examine caselaw where the person trying to make a claim was turned down, and try to extract the facts that were the cause of it.

**Comment by arekmano** [comment] 2017-10-16 02:50
We can then create 2 individual "EPIC" user stories one for each method. Each of these would then be split into user stories where we can perform work.

**Comment by arekmano** [comment] 2017-10-19 04:23
We would absolutely need a list of general receivability criteria. Based on the criteria, we can add new user stories. Otherwise, this story will still remain vague.

**Comment by arekmano** [comment] 2017-10-30 02:20
Closing as new user stories will be added for each claim type. See #82 #80 #84.

**Closed as completed by arekmano** 2017-10-30 02:20 UTC
Labels: Incomplete, Risk (High), Priority (High), Points (100), Points (?), PO Input Needed, Cancelled
